[variables]
NIXPACKS_PYTHON_VERSION = "3.11"

[phases.install]
cmds = ["pip install --no-cache-dir setuptools wheel", "pip install --no-cache-dir -r requirements.txt"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"
